services:
  ai_service: 
    build: 
      context: .
      dockerfile: ./Dockerfile.yml

    env_file: ".env"
   
    ports: 
      - "8000:8000"
    networks:
      - tranquara-network
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tranquara-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 20s
      retries: 4
  qdrant:
    container_name: qdrant_local
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - tranquara-network
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
networks:
  tranquara-network:
    external: true