FROM python:3.10-slim

WORKDIR /app

#install all requirements
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY . /app
EXPOSE 8000

CMD ["python",  "-u" ,"main.py"]