services:
  ai_service: 
    build: 
      context: .
      dockerfile: ./Dockerfile.yml
    ports: 
      - "8000:8000"
    networks:
      - tranquara-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tranquara-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 20s
      retries: 4

  mongodb: 
    image: "mongo"
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=tranquara_ai_service
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=Nhatdien123
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 15s
      retries: 4
      timeout: 20s

networks:
  tranquara-network:
    external: true