"""
Prep Pack Router

POST /api/prep-pack — Generates an AI Therapy Session Prep Pack.

Data flow:
  1. Frontend calls this endpoint with user_id + date range
  2. Journals are fetched directly from Qdrant (synced via RabbitMQ pipeline)
  3. AI memories are fetched directly from Qdrant
  4. GPT generates structured prep pack
  5. Returns prep pack JSON to frontend

Note: Journals land in Qdrant via the existing RabbitMQ pipeline:
  Go backend → ai_tasks queue → journal.index event → Qdrant indexing
  Memories are generated by the memory scheduler and stored in Qdrant.
"""

from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from database.vector_database import (
    get_user_journals_by_date_range,
    get_all_user_memories,
)
from service.ai_service_processor import AIProcessor

router = APIRouter()


class PrepPackRequest(BaseModel):
    user_id: str
    date_range_start: str  # ISO date string (e.g. "2026-03-01")
    date_range_end: str    # ISO date string (e.g. "2026-03-11")
    language: str = "en"


@router.post("/api/prep-pack")
async def generate_prep_pack(request: PrepPackRequest):
    """Generate an AI Therapy Session Prep Pack from Qdrant-stored journals + memories."""

    # 1. Fetch journals from Qdrant (already synced via RabbitMQ pipeline)
    journals = get_user_journals_by_date_range(
        user_id=request.user_id,
        date_start=request.date_range_start,
        date_end=request.date_range_end,
    )

    if not journals:
        raise HTTPException(
            status_code=400,
            detail="No journal entries found for the selected date range."
        )

    # 2. Fetch AI memories from Qdrant
    raw_memories = get_all_user_memories(request.user_id)
    memories = [
        point.payload.get("page_content", "")
        for point in raw_memories
        if point.payload and point.payload.get("page_content")
    ]

    # 3. Generate prep pack via GPT
    try:
        ai_processor = AIProcessor()
        prep_pack = ai_processor.generate_prep_pack(
            journal_entries=journals,
            memories=memories,
            language=request.language,
        )

        return {
            "prep_pack": prep_pack,
            "meta": {
                "journals_analyzed": len(journals),
                "date_range": f"{request.date_range_start} – {request.date_range_end}",
                "generated_at": datetime.now(timezone.utc).isoformat(),
            }
        }

    except ValueError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        print(f"[prep-pack] Unexpected error: {e}")
        raise HTTPException(
            status_code=500,
            detail="Failed to generate prep pack. Please try again."
        )
